BoardProject2/boardRoot/board/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('noticeboard/', include('noticeboard.urls')),
]

BoardProject2/boardRoot/noticeboard/urls.py
from django.urls import path
from . import views

app_name = 'noticeboard'
urlpatterns = [
    path('', views.index, name='index'),
    path('write/', views.write_article, name='write_article'),
    path('add/', views.add_article, name='add_article'),
    path('<int:article_id>/', views.view_article, name='view'),
    path('update/<int:article_id>/', views.update_article, name='update'),
    path('delete/<int:article_id>/', views.delete_article, name='delete'),
]

BoardProject2/boardRoot/noticeboard/models.py
from django.db import models
from django.utils.timezone import now

class Notice(models.Model):
    title = models.CharField(max_length=100)
    content = models.CharField(max_length=2000)
    writeDate = models.DateTimeField(default=now, editable=False)
    writeID = models.CharField(max_length=50)

    def __str__(self):
        return self.title



# Create your models here.

BoardProject2/boardRoot/noticeboard/views.py
from django.shortcuts import render, get_object_or_404
from noticeboard.models import Notice
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.utils import timezone

# Create your views here.
def index(request):
    article_list = Notice.objects.all().order_by('-writeDate')
    content = {'article_list': article_list}
    return render(request, 'noticeboard/index.html', content)

def write_article(request):
    return render(request, 'noticeboard/writeArticle.html')

def add_article(request):
    notice = Notice()
    notice.title = request.POST['title']
    notice.content = request.POST['content']
    notice.writeID = 'jinsujinsu'
    notice.save()
    return HttpResponseRedirect(reverse('noticeboard:index'))

def view_article(request, article_id):
    notice = get_object_or_404(Notice, pk=article_id)
    return render(request, 'noticeboard/detail.html', {'article':notice})


def update_article(request, article_id):
    notice = Notice.objects.get(id=article_id)
    # 불법 접근을 막기 위해
    if request.method == 'POST':
        notice.title = request.POST['title']
        notice.content = request.POST['content']
        notice.writeDate = timezone.datetime.now()
        notice.save()
        return HttpResponseRedirect(reverse('noticeboard:view',args={article_id}))
    else:
        return render(request, 'noticeboard/detail.html', {'article': notice})


def delete_article(request, article_id):
    notice = Notice.objects.get(id=article_id)
    notice.delete()
    return HttpResponseRedirect(reverse('noticeboard:index'))

BoardProject2/boardRoot/templates/noticeboard/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글보기</title>
  <style>
    #tr_btn_modify{
    display:none;
    }
    #i-content{
    text-align:left;
    }
  </style>
    <script>
        function backToList(obj){
            obj.action = "{% url 'noticeboard:index' %}";
            obj.submit();
        }

        function fn_enable(obj){
          let modify = document.querySelector('#tr_btn_modify');
          modify.style.display='block';

          let btn = document.querySelector('#tr_btn');
          btn.style.display='none';

          let title_btn = document.querySelector('#i-title');
          title_btn.disabled=false;

          let content_btn = document.querySelector('#i-content');
          content_btn.disabled=false;
          }

          function fn_modify_article(obj){
            obj.action = "{% url 'noticeboard:update' article.id %}";
            obj.submit();
           }

         function fn_remove_article(obj){
            obj.action = "{% url 'noticeboard:delete' article.id %}";
            obj.submit();
           }

    </script>
</head>
<body>
  <form name="frmArticle" method="post">
    {% csrf_token %}
    <table border="0" align="center">
      <tbody>
        <tr>
          <td width="150" align="center" bgcolor="#FF9933">글번호</td>
          <td><input type="text" value="{{article.id}}" disabled /></td>
        </tr>
        <tr>
          <td width="150" align="center" bgcolor="#FF9933">작성자 ID</td>
          <td><input type="text" value="{{article.writeID}}" disabled /></td>
        </tr>
        <tr>
          <td width="150" align="center" bgcolor="#FF9933">제목</td>
          <td><input type="text" value="{{article.title}}" name="title" id="i-title" disabled /></td>
        </tr>
        <tr>
          <td width="150" align="center" bgcolor="#FF9933">내용</td>
          <td><textarea rows="20" cols="60" name="content" id="i-content" disabled >{{article.content}}
          </textarea></td>
        </tr>
        <tr>
          <td width="20" align="center" bgcolor="#FF9933">등록일자</td>
          <td><input type="text" value="{{article.writeDate}}" disabled /></td>
        </tr>
        <tr id="tr_btn_modify">
          <td colspan="2" align="center">
            <input type="button" value="수정반영하기" onclick="fn_modify_article(frmArticle)" />
            <input type="button" value="취소" onclick="backToList(frmArticle)" />
          </td>
        </tr>
        <tr id="tr_btn">
          <td colspan="2" align="center">
          <input type="button" value="수정하기" onclick="fn_enable(this.form)"/>
          <input type="button" value="삭제하기" onclick="fn_remove_article(frmArticle)" />
          <input type="button" value="리스트로 돌아가기" onclick="backToList(this.form)" />
        </tr>
      </tbody>
    </table>
  </form>


</body>
</html>

BoardProject2/boardRoot/templates/noticeboard/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>게시글 목록</title>
    <style>
        .cls1{
        text-decoration: none;
        }
        .cls2{
        text-align : center;
        font-size : 30px;
        display : block;
        }

    </style>
</head>
<body>
    <table align="center" border="1" width="80%">
        <thead>
            <tr height="10" align="center" bgcolor="Lightgreen">
                <th>글번호</th>
                <th>작성자</th>
                <th>제목</th>
                <th>작성일</th>
            </tr>
        </thead>
        {% if article_list%}
        <tbody>
        {% for article in article_list%}
            <tr align="center">
                <td width="5%">{{forloop.counter}}</td>
                <td width="10%">{{article.writeID}}</td>
                <td align="left" width="35%">
                    <span style="padding-right:30px"></span>
                    <a class="cls1" href="{% url 'noticeboard:view' article.id %}">{{article.title}}</a>
                </td>
                <td width="10%">{{article.writeDate}}</td>
            </tr>
        {% endfor %}
        </tbody>
        {% else %}
        <tbody>
            <tr height="80">
                <td colspan="4">
                    <p align="center">
                        <b><span style="font-size:15px;">등록된 글이 없습니다.</span></b>
                    </p>
                </td>
            </tr>
        </tbody>
        {% endif %}
    </table>
    <a class="cls1" href="{% url 'noticeboard:write_article'%}">
        <span class="cls2">글쓰기</span>
    </a>
</body>
</html>

BoardProject2/boardRoot/templates/noticeboard/writeArticle.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>글 작성</title>
    <script>
        function backToList(obj){
            obj.action = "{% url 'noticeboard:index' %}";
            obj.submit();
        }
    </script>
</head>
<body>
    <h1 style="text-align:center">새글 쓰기</h1>
    <form name="articleForm" method="post" action="{% url 'noticeboard:add_article'%}">
      {% csrf_token %}
      <table border="0" align="center">
        <tbody>
          <tr>
            <td align="right">글제목:</td>
            <td colspan="2"><input type="text" size="70" maxlength="90" name="title"></td>
          </tr>
          <tr>
            <td align="right" valign="top"><br>글내용:</td>
            <td colspan="2"><textarea name="content" cols="72" rows="10" maxlength="1900"></textarea></td>
          </tr>
          <tr>
            <td align="right"></td>
            <td colspan="2">
              <input type="submit" value="글쓰기" />
              <input type="submit" value="목록보기" onclick="backToList(this.form)">
            </td>
          </tr>
        </tbody>
      </table>
    </form>
</body>
</html>